### ISSUE TITLE
cinecturlink version 1.1.1

### ISSUE THREAD

**Issue by pidlas** [JcDenis/cinecturlink2#1]
Bonjour et merci de votre retour,

La version dotclear : 2.24.1
Le version PHP de dotclear2 : 7.4

Le plugin donne une erreur si le tri se fait sur Aléatoire. Le message d'erreur s'affiche en clair dans le widget : https://sante9naturel.fr/. L'affichage des autres liens donne une multitude d'erreurs.

La première erreur sur le critère de tri : https://paste.yunohost.org/yuvogemuru.pas

Les autres sur l'affichage des autres liens : https://paste.yunohost.org/dexeredaye.pas

Si les liens ne sont plus valides merci de me le signaler.

Bien à vous

**Comment by JcDenis** [comment]
[plugin-cinecturlink2.zip](https://github.com/JcDenis/cinecturlink2/files/12439352/plugin-cinecturlink2.zip)
J'ai fait une correction sur cette version 1.1.1 dispo en lien de mon commentaire, mais je n'ai pas testé, ça me fait remonter trop en arrière dans les versions Dotclear.

Et c'est corrigé pour la version 2.0 mais qui nécessite Dotclear 2.27

**Comment by pidlas** [comment]
Bonjour,

Je rencontre un problème d'affichage lorsque je veux afficher ('Plus de liens'), l'ensemble des 'cinecturlinks' sur la page entière. Les images s'affichent en décalé vers la droite. J'ai essayé de régler le problème en jouant les propriétés CSS mais je n'arrive pas à accéder à la propriété 'width:100%' de élément{}.
Je souhaiterais que chaque lien s'affiche les uns en dessous les autres comme deux blocs qui s'afficheraient l'un en dessous l'autre.
Dans l'inspecteur j'y arrive en modifiant le lien de l'image pour que l'image qui s'affiche soit le thumbernail, en décochant la largeur et en ajouter une marge haute de 35px sur le titre 'h2'.
Mais comme je le dis plus haut, je n'arrive pas à modifier le width: 100% qui semble être codé directement dans le php.

Il y a surement un autre moyen plus élégant pour réaliser cela et c'est pourquoi je vous soumets ce petit problème d'affichage.

Je vais activer le plugin sur mon blog https://sante9naturel.fr pour que vous puissiez vous rendre compte du problème par vous-même. Quand cela est fait, pourriez-vous me le signaler pour que je supprime l'accès aux liens sur mon blog en live.

Bien à vous,

Q

**Comment by JcDenis** [comment]
Je vois également que cinecturlink pose problème avec d'autre plugin, je vais regarder ça.

Pour la présentation, je suis plutôt mauvais en style, mais la seule règle CSS en dur est la taille maximal de l'image (et non son placement) qui peut être modifiée dans les réglages du plugin dans les paramètres du blog. (eput-etre vider le cache de template pour que ça prenne effet)

Et au cas ou, plugin reprend la trame des tplset dotty ou musttek suivant le thème utilisé. (voir les fichier default-templates/xxx/cinecturlink2.html du plugin.)

**Comment by pidlas** [comment]
Bravo,

Les deux plugins qui posent problème sont Billets connexes (Related Entries) et (AddToAny) parmi ceux que j'ai activé sur mon blog. Merci pour les conseils concernant les tplset. A ce sujet, où puis-je trouver de la doc. sur les tplset. Une doc. un peu fouillée. J'aimerai comprendre comment le moteur dotclear2 fonctionne et comment donc modifier des templates en respectant les règles de programmation.

**Comment by JcDenis** [comment]
Pour les plugins, je pense qu'en modififant le miens, il serait possible d'éradiquer ces erreurs. (reflexion en cours)

Pour de l'aide sur les thèmes / templates, comme dit plus haut, je ne suis vraiment pas expert. Même si ça date un peu (voir même beaucoup), il y a de l'aide sur https://tips.dotaddict.org/ et https://fr.dotclear.org/documentation/2.0/resources/themes ça peut toujours donner une idée en comparant avec ce qui existe en réel aujourd'hui.
